version: "3"
services:
  frontend:
    build:
      context: ./front
    container_name: "frontend"
    volumes:
      - ./front/src:/app/src
    ports:
      - "4200:4200"
    networks:
      - mynetwork
  backend:
    build:
      context: ./back
    container_name: "backend"
    volumes:
        - ./back:/app
    ports:
      - "5000:5000"
    networks:
      - mynetwork
networks:
  mynetwork: